version: "3"

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - mongo_data:/data/db
    ports:
      - "27020:27017"

volumes:
  mongo_data:
